wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.36.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705055870.813938
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 50
      - 55
      - 103
      - 105
      3:
      - 7
      - 23
      4: 3.11.7
      5: 0.16.1
      6: 4.36.2
      8:
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
config:
  desc: null
  value: '{''hyperparameters'': {''lr'': 0.001, ''batch_size'': 16, ''epochs'': 5,
    ''hidden1'': 512, ''hidden2'': 256, ''num_workers'': 3}, ''data_path'': ''data/processed'',
    ''criterion'': ''MSELoss'', ''optimizer'': ''Adam''}'
